apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-storage
spec:
  resources:
    requests:
      storage: 200Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: default